### ISSUE TITLE
broken error string?

### ISSUE THREAD

**Issue by walterbender** [sugarlabs/aslo#17]
When trying to upload a bundle an unhelpful, opaque error message is reported:

 "The file */activity/activity.info must contain a value for $key attribute."

I assume that $key is supposed to be replaced by a string so as to report which field is missing or malformed.

The bundle in question was generated from this repo:

https://github.com/Pro-Panda/CowBulls-activity

**Comment by quozl** [comment]
The message occurs if license is missing, and @Pro-Panda has since fixed that in 
https://github.com/Pro-Panda/CowBulls-activity/commit/94a05e925272e6e919697bb18170f3c92cbc661e#diff-65fbf29894b41250d50ea32939f0a6d9

**Comment by quozl** [comment]
Actually, it was also a metadata typo, `licence` instead of `license`.
