### ISSUE TITLE
does not show latest version of an activity

### ISSUE THREAD

**Issue by quozl** [sugarlabs/aslo#3]
activities.sugarlabs.org does not show the latest available version of an activity.

For example, the Implode activity;
* [search result](http://activities.sugarlabs.org/en-US/sugar/search?q=implode&cat=all) shows May 2012 update, and offers implode-12.xo as download, both of which are incorrect,
* [implode page](http://activities.sugarlabs.org/en-US/sugar/addon/4086) offers the same incorrect information,
* [implode old versions page](http://activities.sugarlabs.org/en-US/sugar/addons/versions/4086) offers the correct implode-17.xo with a date 1st July 2016.

Workaround is to click on "old versions" to find the latest version.

**Comment by quozl** [comment]
caused by SITE_SUGAR_STABLE in aslo/config.php not updated by sugar release.

**Comment by quozl** [comment]
Recent release of Write-98 has made an opportunity for testing.

Write-98 is listed in ASLO as compatible with Sugar 0.110 down to Sugar 0.96.

Browse running under Sugar 0.110 has ASLO correctly showing Write-98 as latest version of Write.  This is because HTTP GET request contains User-Agent of SugarLabs/0.110, and ASLO correctly interprets the Sugar version.

Firefox running under Sugar 0.110 has ASLO incorrectly showing Write-79 as latest version of Write.  This is because the User-Agent is not used to convey the Sugar version.  ASLO uses a default value in `aslo/config.php` which is likely to be 0.86, because that's what is in git.  Write-79 is the last version of Write which supported 0.86.

So everything is running as designed except the default value has not been maintained.

I've asked on [systems@](http://lists.sugarlabs.org/archive/systems/2017-April/005437.html) for someone with access to read the configuration file.

**Comment by tony37** [comment]
For Browse as an integral part of Sugar,  it is acceptable to show which version applies to a specific Sugar release. 

However, for activities in general, this is wrong. The latest version (highest version number) should be shown. Activity developers should attempt to build the activity to run in all versions of Sugar. 

Obviously, maintenance will be required from time to time as the Sugar upstream changes the packages/modules included in the Sugar release.

**Comment by quozl** [comment]
I don't understand your point.

**Comment by tony37** [comment]
If a new version of TurtleBlocks is released to ASLO, there is no reason not to show that version number to 
browsers. 

Your comments suggest that a version change after a Sugar release will not work on that release and therefore the user should not see that version.

**Comment by quozl** [comment]
The reason not to show a new version of TurtleBlocks in ASLO is if the version of Sugar being used is not supported by the new version of TurtleBlocks.  That design goal works well in ASLO when Browse is used inside Sugar.  The goal does not work when people use other browsers; because ASLO assumes you are using Sugar 0.86 (exact value yet to be confirmed by someone with access).

> Your comments suggest that a version change after a Sugar release will not work on that release and therefore the user should not see that version.

Not *will* but *may*.

**Comment by scanterog** [comment]
I can confirm SITE_SUGAR_STABLE is defined as 0.86.

**Comment by icarito** [comment]
Please, grant me access?

Regards,

Sebastian

**Comment by scanterog** [comment]
PR #11 merged but still can confirm same behavior. @icarito access granted.

**Comment by quozl** [comment]
Thanks.  Looks like tighter debugging is needed; which I can't help directly with because I've no access ... I suggest you add some code to display SITE_SUGAR_STABLE or test what value it has, and if it is not 0.110 there must be some cause yet to discover.

**Comment by scanterog** [comment]
Fixed! It was changed in wrong place. It needs to be change at `site/app/config/config.php` which is not included into git (check .gitignore).

**Comment by quozl** [comment]
https://wiki.sugarlabs.org/go/Development_Team/Release#Glucose_.28base.29_modules updated.

**Comment by icarito** [comment]
Hi @scg could you please remove my password on ASLO and grant my user
sudo access? Thanks in advance.

**Comment by icarito** [comment]
Ah, nevermind, I got access. Thanks!
